### PR TITLE
String interpolation puzzler

### PR DESCRIPTION
**Pull request by demobox**
@marconilanna: Fooled quite a lot of attendees at NE Scala ;-)

### CODE REVIEW

**Comment by marconilanna** [comment]
lgtm. related: try as you might, there is no way to generate the string `\ua0a0` (of length 6) using triple quotes

```scala
scala> "\ua0a0"
res0: String = ꂠ

scala> "\\ua0a0"
res1: String = \ua0a0

scala> """\ua0a0"""
res2: String = ꂠ

scala> """\\ua0a0"""
res3: String = \\ua0a0
```

**Comment by demobox** [comment]
> try as you might, there is no way to generate the string \ua0a0 (of length 6) using triple quotes

@marconilanna: How about:

```
scala> """\u005cua0a0""" // U+005C == '\'
res8: String = \ua0a0
```

?

**Comment by marconilanna** [comment]
witchcraft!

**Comment by demobox** [comment]
> witchcraft!

Not exactly pretty or intuitive, no... ;-)

**Comment by demobox** [comment]
Merged to master: e4875cf3358

**Pull request closed without merging**
