### PR TITLE
First draft of a string split puzzler

### PR DESCRIPTION
**Pull request by demobox**
Motivated by https://twitter.com/extempore2/status/543851869265596416

### CODE REVIEW

**Comment by demobox** [comment]
@nermin: I know you weren't a great fan of this in the form that's in the Tweet that gave rise to this. Here, I've tried to use a method that exists only in Scala, making this a little similar to ['$!.*% Iterators!'](http://scalapuzzlers.com/#pzzlr-025) in the sense that it's weirdness you observe in Scala that is based on underlying Java behaviour.

**Comment by demobox** [comment]
@nermin: Ping..?

**Comment by nermin** [comment]
This would definitely not be the first puzzler caused by inherent Java behavior (I believe we have at least a couple), so from that perspective it's a fair game. I still don't find much to learn from this one, but I am also not opposed to publishing it. You did a nice job @demobox of creating a better puzzler from the original tweet.

**Comment by demobox** [comment]
> I still don't find much to learn from this one

Agreed - string splitting is probably quite a common operation, but this is not something you're likely to run into all that often. Thanks for the review, @nermin!

**Comment by demobox** [comment]
Merged to master: ca32f51

**Pull request closed without merging**
